---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devops
    server: https://kubernetes.default.svc
  project: my-app-of-apps
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 3.9.0
    helm:
      parameters: []
      # Values file as block file
      # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
      values: |
        controller:
          installPlugins:
            - kubernetes:1.30.1
            - workflow-aggregator:2.6
            - git:4.9.0
            - configuration-as-code:1.54